/********************************************************************************
** Form generated from reading UI file 'EmployeeRecordView.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EMPLOYEERECORDVIEW_H
#define UI_EMPLOYEERECORDVIEW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QVBoxLayout>

QT_BEGIN_NAMESPACE

class Ui_EmployeeRecordView
{
public:
    QVBoxLayout *verticalLayout;
    QVBoxLayout *verticalLayout_2;
    QGroupBox *personalInfo_groupBox;
    QGridLayout *gridLayout_2;
    QHBoxLayout *horizontalLayout_8;
    QLabel *education_label;
    QLineEdit *education_lineEdit;
    QHBoxLayout *horizontalLayout_4;
    QLabel *dob_label;
    QDateEdit *dob_dateEdit;
    QHBoxLayout *horizontalLayout_6;
    QLabel *phone_label;
    QLineEdit *phone_lineEdit;
    QHBoxLayout *horizontalLayout_2;
    QLabel *name_label;
    QLineEdit *name_lineEdit;
    QHBoxLayout *horizontalLayout_3;
    QLabel *gender_label;
    QComboBox *gender_comboBox;
    QHBoxLayout *horizontalLayout_7;
    QLabel *salary_label;
    QDoubleSpinBox *salary_doubleSpinBox;
    QHBoxLayout *horizontalLayout_1;
    QLabel *id_label;
    QLineEdit *id_lineEdit;
    QHBoxLayout *horizontalLayout_5;
    QLabel *address_label;
    QLineEdit *address_lineEdit;
    QHBoxLayout *horizontalLayout_9;
    QLabel *role_label;
    QComboBox *role_comboBox;
    QGroupBox *detailInfo_groupBox;
    QGridLayout *gridLayout;
    QHBoxLayout *specialty_horizontalLayout;
    QLabel *specialty_label;
    QLineEdit *specialty_lineEdit;
    QHBoxLayout *subsidies_horizontalLayout;
    QLabel *subsidies_label;
    QDoubleSpinBox *subsidies_doubleSpinBox;
    QHBoxLayout *duty_horizontalLayout;
    QLabel *duty_label;
    QLineEdit *duty_lineEdit;
    QHBoxLayout *license_horizontalLayout;
    QLabel *license_label;
    QLineEdit *license_lineEdit;
    QHBoxLayout *workingDays_horizontalLayout;
    QLabel *workingDays_label;
    QSpinBox *workingDays_spinBox;
    QDialogButtonBox *buttonBox;

    void setupUi(QDialog *EmployeeRecordView)
    {
        if (EmployeeRecordView->objectName().isEmpty())
            EmployeeRecordView->setObjectName(QString::fromUtf8("EmployeeRecordView"));
        EmployeeRecordView->resize(800, 450);
        EmployeeRecordView->setStyleSheet(QString::fromUtf8("/* ---------------------------------------------------------------------------\n"
"\n"
"    WARNING! File created programmatically. All changes made in this file will be lost!\n"
"\n"
"    Created by the qtsass compiler v0.4.0\n"
"\n"
"    The definitions are in the \"qdarkstyle.qss._styles.scss\" module\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* Light Style - QDarkStyleSheet ------------------------------------------ */\n"
"/*\n"
"\n"
"See Qt documentation:\n"
"\n"
"  - https://doc.qt.io/qt-5/stylesheet.html\n"
"  - https://doc.qt.io/qt-5/stylesheet-reference.html\n"
"  - https://doc.qt.io/qt-5/stylesheet-examples.html\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* Reset elements ------------------------------------------------------------\n"
"\n"
"Resetting everything helps to unify styles across different operating systems\n"
"\n"
"--------------------------------------------------------------------------- */"
                        "\n"
"* {\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"  border: 0px;\n"
"  border-style: none;\n"
"  border-image: none;\n"
"  outline: 0;\n"
"  font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* specific reset for elements inside QToolBar */\n"
"QToolBar * {\n"
"  margin: 0px;\n"
"  padding: 0px;\n"
"}\n"
"\n"
"/* QWidget ----------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QWidget {\n"
"  background-color: #FAFAFA;\n"
"  border: 0px solid #C0C4C8;\n"
"  padding: 0px;\n"
"  color: #19232D;\n"
"  selection-background-color: #9FCBFF;\n"
"  selection-color: #19232D;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"  background-color: #FAFAFA;\n"
"  color: #9DA9B5;\n"
"  selection-background-color: #DAEDFF;\n"
"  selection-color: #9DA9B5;\n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"  background-color: #9FCBFF;\n"
"}\n"
"\n"
"QWidget::item:hover:!selected {\n"
"  background-color: #73C7FF;\n"
"}\n"
"\n"
"/* QMainWindow --------------"
                        "----------------------------------------------\n"
"\n"
"This adjusts the splitter in the dock widget, not qsplitter\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmainwindow\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMainWindow::separator {\n"
"  background-color: #C0C4C8;\n"
"  border: 0px solid #FAFAFA;\n"
"  spacing: 0px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"  background-color: #ACB1B6;\n"
"  border: 0px solid #73C7FF;\n"
"}\n"
"\n"
"QMainWindow::separator:horizontal {\n"
"  width: 5px;\n"
"  margin-top: 2px;\n"
"  margin-bottom: 2px;\n"
"  image: url(\":/qss_icons/light/rc_light/toolbar_separator_vertical.png\");\n"
"}\n"
"\n"
"QMainWindow::separator:vertical {\n"
"  height: 5px;\n"
"  margin-left: 2px;\n"
"  margin-right: 2px;\n"
"  image: url(\":/qss_icons/light/rc_light/toolbar_separator_horizontal.png\");\n"
"}\n"
"\n"
"/* QToolTip ---------------------------------------------------------------\n"
"\n"
""
                        "https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtooltip\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolTip {\n"
"  background-color: #9FCBFF;\n"
"  color: #19232D;\n"
"  /* If you remove the border property, background stops working on Windows */\n"
"  border: none;\n"
"  /* Remove padding, for fix combo box tooltip */\n"
"  padding: 0px;\n"
"  /* Remove opacity, fix #174 - may need to use RGBA */\n"
"}\n"
"\n"
"/* QStatusBar -------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qstatusbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QStatusBar {\n"
"  border: 1px solid #C0C4C8;\n"
"  /* Fixes Spyder #9120, #9121 */\n"
"  background: #C0C4C8;\n"
"  /* Fixes #205, white vertical borders separating items */\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"  border: none;\n"
"}\n"
"\n"
"QStatusBar QToolTip {\n"
"  background-color: #73C7FF;"
                        "\n"
"  border: 1px solid #FAFAFA;\n"
"  color: #FAFAFA;\n"
"  /* Remove padding, for fix combo box tooltip */\n"
"  padding: 0px;\n"
"  /* Reducing transparency to read better */\n"
"  opacity: 230;\n"
"}\n"
"\n"
"QStatusBar QLabel {\n"
"  /* Fixes Spyder #9120, #9121 */\n"
"  background: transparent;\n"
"}\n"
"\n"
"/* QCheckBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcheckbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCheckBox {\n"
"  background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"  spacing: 4px;\n"
"  outline: none;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"}\n"
"\n"
"QCheckBox:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QCheckBox QWidget:disabled {\n"
"  background-color: #FAFAFA;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"  margin-left: 2px;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
""
                        "  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover, QCheckBox::indicator:unchecked:focus, QCheckBox::indicator:unchecked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked_focus.png\");\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked.png\");\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover, QCheckBox::indicator:checked:focus, QCheckBox::indicator:checked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked_disabled.png\");\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_inde"
                        "terminate.png\");\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_indeterminate_disabled.png\");\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:focus, QCheckBox::indicator:indeterminate:hover, QCheckBox::indicator:indeterminate:pressed {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_indeterminate_focus.png\");\n"
"}\n"
"\n"
"/* QGroupBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qgroupbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QGroupBox {\n"
"  font-weight: bold;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  margin-top: 6px;\n"
"  margin-bottom: 4px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  subcontrol-origin: margin;\n"
"  subcontrol-position: top left;\n"
"  left: 4px;\n"
"  padding-left: 2px;\n"
"  padding-right: 4px;\n"
"  padding-top: -4px;\n"
"}\n"
""
                        "\n"
"QGroupBox::indicator {\n"
"  margin-left: 2px;\n"
"  margin-top: 2px;\n"
"  padding: 0;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked:hover, QGroupBox::indicator:unchecked:focus, QGroupBox::indicator:unchecked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked_focus.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:checked {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:checked:hover, QGroupBox::indicator:checked:focus, QGroupBox::indicator:checked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QGroupB"
                        "ox::indicator:checked:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked_disabled.png\");\n"
"}\n"
"\n"
"/* QRadioButton -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qradiobutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QRadioButton {\n"
"  background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"  spacing: 4px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"  border: none;\n"
"  outline: none;\n"
"}\n"
"\n"
"QRadioButton:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QRadioButton:disabled {\n"
"  background-color: #FAFAFA;\n"
"  color: #9DA9B5;\n"
"  border: none;\n"
"  outline: none;\n"
"}\n"
"\n"
"QRadioButton QWidget {\n"
"  background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"  spacing: 0px;\n"
"  padding: 0px;\n"
"  outline: none;\n"
"  border: none;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"  border: none;\n"
"  outline: none;\n"
"  margin-left:"
                        " 2px;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  image: url(\":/qss_icons/light/rc_light/radio_unchecked.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover, QRadioButton::indicator:unchecked:focus, QRadioButton::indicator:unchecked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/light/rc_light/radio_unchecked_focus.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/radio_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/light/rc_light/radio_checked.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover, QRadioButton::indicator:checked:focus, QRadioButton::indicator:checked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/light/rc_light/radio_checked_focus.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:disable"
                        "d {\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/light/rc_light/radio_checked_disabled.png\");\n"
"}\n"
"\n"
"/* QMenuBar ---------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmenubar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMenuBar {\n"
"  background-color: #C0C4C8;\n"
"  padding: 2px;\n"
"  border: 1px solid #FAFAFA;\n"
"  color: #19232D;\n"
"  selection-background-color: #73C7FF;\n"
"}\n"
"\n"
"QMenuBar:focus {\n"
"  border: 1px solid #9FCBFF;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"  background: transparent;\n"
"  padding: 4px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"  padding: 4px;\n"
"  background: transparent;\n"
"  border: 0px solid #C0C4C8;\n"
"  background-color: #73C7FF;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"  padding: 4px;\n"
"  border: 0px solid #C0C4C8;\n"
"  background-color: #73C7FF;\n"
"  color: #19232D;\n"
"  margin-bottom: 0px;\n"
"  padding-bottom"
                        ": 0px;\n"
"}\n"
"\n"
"/* QMenu ------------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmenu\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMenu {\n"
"  border: 0px solid #C0C4C8;\n"
"  color: #19232D;\n"
"  margin: 0px;\n"
"  background-color: #D2D5D8;\n"
"  selection-background-color: #73C7FF;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"  height: 1px;\n"
"  background-color: #ACB1B6;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QMenu::item {\n"
"  background-color: #D2D5D8;\n"
"  padding: 4px 24px 4px 28px;\n"
"  /* Reserve space for selection border */\n"
"  border: 1px transparent #C0C4C8;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"  color: #19232D;\n"
"  background-color: #73C7FF;\n"
"}\n"
"\n"
"QMenu::item:pressed {\n"
"  background-color: #73C7FF;\n"
"}\n"
"\n"
"QMenu::item:disabled {\n"
"  background-color: #D2D5D8;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QMenu::icon {\n"
"  padding-left: 10px;\n"
""
                        "  width: 14px;\n"
"  height: 14px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"  padding-left: 8px;\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  /* non-exclusive indicator = check box style indicator (see QActionGroup::setExclusive) */\n"
"  /* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:hover, QMenu::indicator:non-exclusive:unchecked:focus, QMenu::indicator:non-exclusive:unchecked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked.png\");\n"
"}\n"
"\n"
"QMenu::indicator"
                        ":non-exclusive:checked:hover, QMenu::indicator:non-exclusive:checked:focus, QMenu::indicator:non-exclusive:checked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:indeterminate {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_indeterminate.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:indeterminate:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_indeterminate_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:indeterminate:focus, QMenu::indicator:non-exclusive:indeterminate:hover, QMenu::indicator:non-exclusive:indeterminate:pressed {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_indeterminate_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked {\n"
"  image: url(\":/qss_icons/light/rc_light/radio"
                        "_unchecked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:hover, QMenu::indicator:exclusive:unchecked:focus, QMenu::indicator:exclusive:unchecked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/light/rc_light/radio_unchecked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/radio_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/light/rc_light/radio_checked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:hover, QMenu::indicator:exclusive:checked:focus, QMenu::indicator:exclusive:checked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/light/rc_light/radio_checked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:disabled {\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/light/rc_light/radio_checked_disabled.png\");\n"
"}\n"
"\n"
"QMe"
                        "nu::right-arrow {\n"
"  margin: 5px;\n"
"  padding-left: 12px;\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"}\n"
"\n"
"/* QAbstractItemView ------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcombobox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractItemView {\n"
"  alternate-background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QAbstractItemView QLineEdit {\n"
"  padding: 2px;\n"
"}\n"
"\n"
"/* QAbstractScrollArea ----------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qabstractscrollarea\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractScrollArea {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
""
                        "  /* fix #159 */\n"
"  padding: 2px;\n"
"  /* remove min-height to fix #244 */\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QAbstractScrollArea:disabled {\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* QScrollArea ------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QScrollArea QWidget QWidget:disabled {\n"
"  background-color: #FAFAFA;\n"
"}\n"
"\n"
"/* QScrollBar -------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qscrollbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QScrollBar:horizontal {\n"
"  height: 16px;\n"
"  margin: 2px 16px 2px 16px;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"  background-color: #FAFAFA;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"  background-color: #FAFAFA;\n"
"  width: 16px;\n"
"  margin: 16px 2px 16px 2px;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-r"
                        "adius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  background-color: #ACB1B6;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background-color: #9FCBFF;\n"
"  border: #9FCBFF;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  background-color: #ACB1B6;\n"
"  border: 1px solid #C0C4C8;\n"
"  min-height: 8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"  background-color: #9FCBFF;\n"
"  border: #9FCBFF;\n"
"  border-radius: 4px;\n"
"  min-height: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"  margin: 0px 0px 0px 0px;\n"
"  border-image: url(\":/qss_icons/light/rc_light/arrow_right_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  su"
                        "bcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover, QScrollBar::add-line:horizontal:on {\n"
"  border-image: url(\":/qss_icons/light/rc_light/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\":/qss_icons/light/rc_light/arrow_down_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on {\n"
"  border-image: url(\":/qss_icons/light/rc_light/arrow_down.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"  margin: 0px 3px 0px 3px;\n"
"  border-image: url(\":/qss_icons/light/rc_light/arrow_left_disabled.png\");\n"
""
                        "  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on {\n"
"  border-image: url(\":/qss_icons/light/rc_light/arrow_left.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\":/qss_icons/light/rc_light/arrow_up_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover, QScrollBar::sub-line:vertical:on {\n"
"  border-image: url(\":/qss_icons/light/rc_light/arrow_up.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar:"
                        ":up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"/* QTextEdit --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-specific-widgets\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTextEdit {\n"
"  background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QTextEdit:selected {\n"
"  background: #9FCBFF;\n"
"  color: #C0C4C8;\n"
"}\n"
"\n"
"/* QPlainTextEdit ---------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QPlainText"
                        "Edit {\n"
"  background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QPlainTextEdit:selected {\n"
"  background: #9FCBFF;\n"
"  color: #C0C4C8;\n"
"}\n"
"\n"
"/* QSizeGrip --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qsizegrip\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QSizeGrip {\n"
"  background: transparent;\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  image: url(\":/qss_icons/light/rc_light/window_grip.png\");\n"
"}\n"
"\n"
"/* QStackedWidget ---------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QStackedWidget {\n"
"  padding: 2px;\n"
"  border: 1px solid #C0C4C8;\n"
"  border: 1px solid #FAFAFA;\n"
"}\n"
"\n"
"/* QToolBar --------------------"
                        "-------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolBar {\n"
"  background-color: #C0C4C8;\n"
"  border-bottom: 1px solid #FAFAFA;\n"
"  padding: 1px;\n"
"  font-weight: bold;\n"
"  spacing: 2px;\n"
"}\n"
"\n"
"QToolBar:disabled {\n"
"  /* Fixes #272 */\n"
"  background-color: #C0C4C8;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"  width: 16px;\n"
"  image: url(\":/qss_icons/light/rc_light/toolbar_move_horizontal.png\");\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"  height: 16px;\n"
"  image: url(\":/qss_icons/light/rc_light/toolbar_move_vertical.png\");\n"
"}\n"
"\n"
"QToolBar::separator:horizontal {\n"
"  width: 16px;\n"
"  image: url(\":/qss_icons/light/rc_light/toolbar_separator_horizontal.png\");\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"  height: 16px;\n"
"  image: url(\":/qss_icons/light/rc_light/toolbar_separator_vertical.p"
                        "ng\");\n"
"}\n"
"\n"
"QToolButton#qt_toolbar_ext_button {\n"
"  background: #C0C4C8;\n"
"  border: 0px;\n"
"  color: #19232D;\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_right.png\");\n"
"}\n"
"\n"
"/* QAbstractSpinBox -------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractSpinBox {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  color: #19232D;\n"
"  /* This fixes 103, 111 */\n"
"  padding-top: 2px;\n"
"  /* This fixes 103, 111 */\n"
"  padding-bottom: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-radius: 4px;\n"
"  /* min-width: 5px; removed to fix 109 */\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button {\n"
"  background-color: transparent #FAFAFA;\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: top right;\n"
"  border-left: 1px solid #C0C4C8;\n"
"  border-bottom: 1px solid #C0C4C8;\n"
"  border-top-left-radius: 0;\n"
"  border-bottom-left-radius: "
                        "0;\n"
"  margin: 1px;\n"
"  width: 12px;\n"
"  margin-bottom: -1px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow, QAbstractSpinBox::up-arrow:disabled, QAbstractSpinBox::up-arrow:off {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_up_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:hover {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_up.png\");\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button {\n"
"  background-color: transparent #FAFAFA;\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: bottom right;\n"
"  border-left: 1px solid #C0C4C8;\n"
"  border-top: 1px solid #C0C4C8;\n"
"  border-top-left-radius: 0;\n"
"  border-bottom-left-radius: 0;\n"
"  margin: 1px;\n"
"  width: 12px;\n"
"  margin-top: -1px;\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow, QAbstractSpinBox::down-arrow:disabled, QAbstractSpinBox::down-arrow:off {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QAbstr"
                        "actSpinBox::down-arrow:hover {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down.png\");\n"
"}\n"
"\n"
"QAbstractSpinBox:hover {\n"
"  border: 1px solid #9FCBFF;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QAbstractSpinBox:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QAbstractSpinBox:selected {\n"
"  background: #9FCBFF;\n"
"  color: #C0C4C8;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* DISPLAYS --------------------------------------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QLabel -----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qframe\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QLabel {\n"
"  background-color: #FAFAFA;\n"
"  border: 0px solid #C0C4C8;\n"
"  padding: 2px;\n"
"  margin: 0px;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QLabel:dis"
                        "abled {\n"
"  background-color: #FAFAFA;\n"
"  border: 0px solid #C0C4C8;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* QTextBrowser -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qabstractscrollarea\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTextBrowser {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTextBrowser:disabled {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTextBrowser:hover, QTextBrowser:!hover, QTextBrowser:selected, QTextBrowser:pressed {\n"
"  border: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"/* QGraphicsView ----------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QGraphicsView {\n"
"  background-color: #FAFAFA;\n"
"  bo"
                        "rder: 1px solid #C0C4C8;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QGraphicsView:disabled {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QGraphicsView:hover, QGraphicsView:!hover, QGraphicsView:selected, QGraphicsView:pressed {\n"
"  border: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"/* QCalendarWidget --------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCalendarWidget {\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QCalendarWidget:disabled {\n"
"  background-color: #FAFAFA;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* QLCDNumber -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QLCDNumber {\n"
"  background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QLCDNumber:disabled {\n"
"  backgrou"
                        "nd-color: #FAFAFA;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* QProgressBar -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qprogressbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QProgressBar {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar:disabled {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"  background-color: #9FCBFF;\n"
"  color: #FAFAFA;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"  background-color: #DAEDFF;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* BUTTONS -------------------------------"
                        "--------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QPushButton ------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qpushbutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QPushButton {\n"
"  background-color: #C0C4C8;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"  border: none;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"  background-color: #C0C4C8;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"  background-color: #73C7FF;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QPushButton:checked:disabled {\n"
"  background-color: #73C7FF;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QPushButton:checked:hover {\n"
"  bac"
                        "kground: #37AEFE;\n"
"}\n"
"\n"
"QPushButton:checked:selected {\n"
"  background: #ACB1B6;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #B4B8BC;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #ACB1B6;\n"
"}\n"
"\n"
"QPushButton:selected {\n"
"  background: #ACB1B6;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QPushButton::menu-indicator {\n"
"  subcontrol-origin: padding;\n"
"  subcontrol-position: bottom right;\n"
"  bottom: 4px;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"  /* Issue #194 #248 - Special case of QPushButton inside dialogs, for better UI */\n"
"  min-width: 80px;\n"
"  min-height: 25px;\n"
"}\n"
"\n"
"/* QToolButton ------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolButton {\n"
"  background-color: #C0C4C8;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"  pa"
                        "dding: 2px;\n"
"  outline: none;\n"
"  border: none;\n"
"  /* The subcontrols below are used only in the DelayedPopup mode */\n"
"  /* The subcontrols below are used only in the MenuButtonPopup mode */\n"
"  /* The subcontrol below is used only in the InstantPopup or DelayedPopup mode */\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"  background-color: #C0C4C8;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"  background-color: #ACB1B6;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton:checked:disabled {\n"
"  background-color: #ACB1B6;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton:checked:hover {\n"
"  background-color: #B4B8BC;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QToolButton:checked:pressed {\n"
"  background-color: #ACB1B6;\n"
"}\n"
"\n"
"QToolButton:checked:selected {\n"
"  background: #ACB1B6;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QToolB"
                        "utton:hover {\n"
"  background-color: #B4B8BC;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"  background-color: #ACB1B6;\n"
"}\n"
"\n"
"QToolButton:selected {\n"
"  background: #ACB1B6;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"0\"] {\n"
"  /* Only for DelayedPopup */\n"
"  padding-right: 2px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] {\n"
"  /* Only for MenuButtonPopup */\n"
"  padding-right: 20px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"]::menu-button {\n"
"  border: none;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"]::menu-button:hover {\n"
"  border: none;\n"
"  border-left: 1px solid #C0C4C8;\n"
"  border-radius: 0;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"2\"] {\n"
"  /* Only for InstantPopup */\n"
"  padding-right: 2px;\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"  padding: 2px;\n"
"  border-radius: 4px;\n"
"  width: 12px;\n"
"  border: none;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton::menu-button:hover {\n"
"  border: 1px solid #9FCBFF;\n"
"}\n"
"\n"
"QToolBu"
                        "tton::menu-button:checked:hover {\n"
"  border: 1px solid #9FCBFF;\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"  top: 0;\n"
"  /* Exclude a shift for better image */\n"
"  left: -2px;\n"
"  /* Shift it a bit */\n"
"}\n"
"\n"
"QToolButton::menu-arrow {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QToolButton::menu-arrow:hover {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down_focus.png\");\n"
"}\n"
"\n"
"/* QCommandLinkButton -----------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCommandLinkButton {\n"
"  background-color: transparent;\n"
"  border: 1px solid #C0C4C8;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QCommandLinkButton:disabled {\n"
"  background-color: transparent;\n"
""
                        "  color: #9DA9B5;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* INPUTS - NO FIELDS ----------------------------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QComboBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcombobox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QComboBox {\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"  selection-background-color: #9FCBFF;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  /* padding-right = 36; 4 + 16*2 See scrollbar size */\n"
"  /* changed to 4px to fix #239 */\n"
"  /* Fixes #103, #111 */\n"
"  min-height: 1.5em;\n"
"  /* padding-top: 2px;     removed to fix #132 */\n"
"  /* padding-bottom: 2px;  removed to fix #132 */\n"
"  /* min-width: 75px;      removed to fix #109 */\n"
"  /* Needed "
                        "to remove indicator - fix #132 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 0;\n"
"  background-color: #FAFAFA;\n"
"  selection-background-color: #9FCBFF;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:hover {\n"
"  background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:selected {\n"
"  background: #9FCBFF;\n"
"  color: #C0C4C8;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:alternate {\n"
"  background: #FAFAFA;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"  background-color: #FAFAFA;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"  border: 1px solid #9FCBFF;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"  selection-background-color: #9FCBFF;\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"  border: none;\n"
"  border-radius: 0;\n"
"  background-color: transparent;\n"
"  selection-background-color: transparent;\n"
"  color: transparent;\n"
"  selection-color: transparent"
                        ";\n"
"  /* Needed to remove indicator - fix #132 */\n"
"}\n"
"\n"
"QComboBox::indicator:alternate {\n"
"  background: #FAFAFA;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"  /* Remove to fix #282, #285 and MR #288*/\n"
"  /*&:checked {\n"
"            font-weight: bold;\n"
"        }\n"
"\n"
"        &:selected {\n"
"            border: 0px solid transparent;\n"
"        }\n"
"        */\n"
"}\n"
"\n"
"QComboBox::item:alternate {\n"
"  background: #FAFAFA;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"  subcontrol-origin: padding;\n"
"  subcontrol-position: top right;\n"
"  width: 12px;\n"
"  border-left: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on, QComboBox::down-arrow:hover, QComboBox::down-arrow:focus {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down.png\");\n"
"}\n"
"\n"
"/* QSlider ----------------------------------------------------------------"
                        "\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qslider\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QSlider:disabled {\n"
"  background: #FAFAFA;\n"
"}\n"
"\n"
"QSlider:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"  background: #C0C4C8;\n"
"  border: 1px solid #C0C4C8;\n"
"  height: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"  background: #C0C4C8;\n"
"  border: 1px solid #C0C4C8;\n"
"  width: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"  background: #9FCBFF;\n"
"  border: 1px solid #C0C4C8;\n"
"  width: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical :disabled {\n"
"  background: #DAEDFF;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"  background: #9FCBFF;\n"
"  border: 1px solid #C0C4C8;\n"
"  height: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
""
                        "\n"
"QSlider::sub-page:horizontal:disabled {\n"
"  background: #DAEDFF;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"  background: #788D9C;\n"
"  border: 1px solid #C0C4C8;\n"
"  width: 8px;\n"
"  height: 8px;\n"
"  margin: -8px 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"  background: #9FCBFF;\n"
"  border: 1px solid #9FCBFF;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"  background: #788D9C;\n"
"  border: 1px solid #C0C4C8;\n"
"  width: 8px;\n"
"  height: 8px;\n"
"  margin: 0 -8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"  background: #9FCBFF;\n"
"  border: 1px solid #9FCBFF;\n"
"}\n"
"\n"
"QSlider::handle:vertical:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"/* QLineEdit --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qlineedit\n"
"\n"
"--------------"
                        "------------------------------------------------------------- */\n"
"QLineEdit {\n"
"  background-color: #FAFAFA;\n"
"  padding-top: 2px;\n"
"  /* This QLineEdit fix  103, 111 */\n"
"  padding-bottom: 2px;\n"
"  /* This QLineEdit fix  103, 111 */\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-style: solid;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"  background-color: #FAFAFA;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 1px solid #9FCBFF;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QLineEdit:selected {\n"
"  background-color: #9FCBFF;\n"
"  color: #C0C4C8;\n"
"}\n"
"\n"
"/* QTabWiget --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtabwidget-and-qtabbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTabWidg"
                        "et {\n"
"  padding: 2px;\n"
"  selection-background-color: #C0C4C8;\n"
"}\n"
"\n"
"QTabWidget QWidget {\n"
"  /* Fixes #189 */\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"  margin: 0px;\n"
"  /* Fixes double border inside pane with pyqt5 */\n"
"  padding: 0px;\n"
"}\n"
"\n"
"QTabWidget::pane:selected {\n"
"  background-color: #C0C4C8;\n"
"  border: 1px solid #9FCBFF;\n"
"}\n"
"\n"
"/* QTabBar ----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtabwidget-and-qtabbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTabBar, QDockWidget QTabBar {\n"
"  qproperty-drawBase: 0;\n"
"  border-radius: 4px;\n"
"  margin: 0px;\n"
"  padding: 2px;\n"
"  border: 0;\n"
"  /* left: 5px; move to the right by 5px - removed for fix */\n"
"}\n"
"\n"
"QTabBar::close-button, QDockWidget QTabBar::close-button {\n"
"  border: 0;\n"
""
                        "  margin: 0;\n"
"  padding: 4px;\n"
"  image: url(\":/qss_icons/light/rc_light/window_close.png\");\n"
"}\n"
"\n"
"QTabBar::close-button:hover, QDockWidget QTabBar::close-button:hover {\n"
"  image: url(\":/qss_icons/light/rc_light/window_close_focus.png\");\n"
"}\n"
"\n"
"QTabBar::close-button:pressed, QDockWidget QTabBar::close-button:pressed {\n"
"  image: url(\":/qss_icons/light/rc_light/window_close_pressed.png\");\n"
"}\n"
"\n"
"QTabBar::tab, QDockWidget QTabBar::tab {\n"
"  /* !selected and disabled ----------------------------------------- */\n"
"  /* selected ------------------------------------------------------- */\n"
"}\n"
"\n"
"QTabBar::tab:top:selected:disabled, QDockWidget QTabBar::tab:top:selected:disabled {\n"
"  border-bottom: 3px solid #DAEDFF;\n"
"  color: #9DA9B5;\n"
"  background-color: #C0C4C8;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected:disabled, QDockWidget QTabBar::tab:bottom:selected:disabled {\n"
"  border-top: 3px solid #DAEDFF;\n"
"  color: #9DA9B5;\n"
"  background-color: #C0C4C8"
                        ";\n"
"}\n"
"\n"
"QTabBar::tab:left:selected:disabled, QDockWidget QTabBar::tab:left:selected:disabled {\n"
"  border-right: 3px solid #DAEDFF;\n"
"  color: #9DA9B5;\n"
"  background-color: #C0C4C8;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected:disabled, QDockWidget QTabBar::tab:right:selected:disabled {\n"
"  border-left: 3px solid #DAEDFF;\n"
"  color: #9DA9B5;\n"
"  background-color: #C0C4C8;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:disabled, QDockWidget QTabBar::tab:top:!selected:disabled {\n"
"  border-bottom: 3px solid #FAFAFA;\n"
"  color: #9DA9B5;\n"
"  background-color: #FAFAFA;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:disabled, QDockWidget QTabBar::tab:bottom:!selected:disabled {\n"
"  border-top: 3px solid #FAFAFA;\n"
"  color: #9DA9B5;\n"
"  background-color: #FAFAFA;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:disabled, QDockWidget QTabBar::tab:left:!selected:disabled {\n"
"  border-right: 3px solid #FAFAFA;\n"
"  color: #9DA9B5;\n"
"  background-color: #FAFAFA;\n"
"}\n"
"\n"
"QTabBar::tab:right:!"
                        "selected:disabled, QDockWidget QTabBar::tab:right:!selected:disabled {\n"
"  border-left: 3px solid #FAFAFA;\n"
"  color: #9DA9B5;\n"
"  background-color: #FAFAFA;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected, QDockWidget QTabBar::tab:top:!selected {\n"
"  border-bottom: 2px solid #FAFAFA;\n"
"  margin-top: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected, QDockWidget QTabBar::tab:bottom:!selected {\n"
"  border-top: 2px solid #FAFAFA;\n"
"  margin-bottom: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected, QDockWidget QTabBar::tab:left:!selected {\n"
"  border-left: 2px solid #FAFAFA;\n"
"  margin-right: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected, QDockWidget QTabBar::tab:right:!selected {\n"
"  border-right: 2px solid #FAFAFA;\n"
"  margin-left: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QDockWidget QTabBar::tab:top {\n"
"  background-color: #C0C4C8;\n"
"  margin-left: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  padding-top: 2px;\n"
"  padding-bottom: 2px;\n"
"  min-width: 5px;\n"
"  border-bot"
                        "tom: 3px solid #C0C4C8;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected, QDockWidget QTabBar::tab:top:selected {\n"
"  background-color: #B4B8BC;\n"
"  border-bottom: 3px solid #37AEFE;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover, QDockWidget QTabBar::tab:top:!selected:hover {\n"
"  border: 1px solid #73C7FF;\n"
"  border-bottom: 3px solid #73C7FF;\n"
"  /* Fixes spyder-ide/spyder#9766 and #243 */\n"
"  padding-left: 3px;\n"
"  padding-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom, QDockWidget QTabBar::tab:bottom {\n"
"  border-top: 3px solid #C0C4C8;\n"
"  background-color: #C0C4C8;\n"
"  margin-left: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  padding-top: 2px;\n"
"  padding-bottom: 2px;\n"
"  border-bottom-left-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"  min-width: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected, QDockWidget QTabBar::tab"
                        ":bottom:selected {\n"
"  background-color: #B4B8BC;\n"
"  border-top: 3px solid #37AEFE;\n"
"  border-bottom-left-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:hover, QDockWidget QTabBar::tab:bottom:!selected:hover {\n"
"  border: 1px solid #73C7FF;\n"
"  border-top: 3px solid #73C7FF;\n"
"  /* Fixes spyder-ide/spyder#9766 and #243 */\n"
"  padding-left: 3px;\n"
"  padding-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QDockWidget QTabBar::tab:left {\n"
"  background-color: #C0C4C8;\n"
"  margin-top: 2px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"  border-top-left-radius: 4px;\n"
"  border-bottom-left-radius: 4px;\n"
"  min-height: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected, QDockWidget QTabBar::tab:left:selected {\n"
"  background-color: #B4B8BC;\n"
"  border-right: 3px solid #37AEFE;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover, QDockWidget QTabBar::tab:left:!selected:hover {\n"
"  border"
                        ": 1px solid #73C7FF;\n"
"  border-right: 3px solid #73C7FF;\n"
"  /* Fixes different behavior #271 */\n"
"  margin-right: 0px;\n"
"  padding-right: -1px;\n"
"}\n"
"\n"
"QTabBar::tab:right, QDockWidget QTabBar::tab:right {\n"
"  background-color: #C0C4C8;\n"
"  margin-top: 2px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"  min-height: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected, QDockWidget QTabBar::tab:right:selected {\n"
"  background-color: #B4B8BC;\n"
"  border-left: 3px solid #37AEFE;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:hover, QDockWidget QTabBar::tab:right:!selected:hover {\n"
"  border: 1px solid #73C7FF;\n"
"  border-left: 3px solid #73C7FF;\n"
"  /* Fixes different behavior #271 */\n"
"  margin-left: 0px;\n"
"  padding-left: 0px;\n"
"}\n"
"\n"
"QTabBar QToolButton, QDockWidget QTabBar QToolButton {\n"
"  /* Fixes #136 */\n"
"  background-color: #C0C4C8;\n"
""
                        "  height: 12px;\n"
"  width: 12px;\n"
"}\n"
"\n"
"QTabBar QToolButton:pressed, QDockWidget QTabBar QToolButton:pressed {\n"
"  background-color: #C0C4C8;\n"
"}\n"
"\n"
"QTabBar QToolButton:pressed:hover, QDockWidget QTabBar QToolButton:pressed:hover {\n"
"  border: 1px solid #9FCBFF;\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:enabled, QDockWidget QTabBar QToolButton::left-arrow:enabled {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_left.png\");\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:disabled, QDockWidget QTabBar QToolButton::left-arrow:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_left_disabled.png\");\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled, QDockWidget QTabBar QToolButton::right-arrow:enabled {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_right.png\");\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled, QDockWidget QTabBar QToolButton::right-arrow:disabled {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_right_disabled.png\");\n"
"}\n"
"\n"
""
                        "/* QDockWiget -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QDockWidget {\n"
"  outline: 1px solid #C0C4C8;\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"  titlebar-close-icon: url(\":/qss_icons/light/rc_light/transparent.png\");\n"
"  titlebar-normal-icon: url(\":/qss_icons/light/rc_light/transparent.png\");\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"  /* Better size for title bar */\n"
"  padding: 3px;\n"
"  spacing: 4px;\n"
"  border: none;\n"
"  background-color: #C0C4C8;\n"
"}\n"
"\n"
"QDockWidget::close-button {\n"
"  icon-size: 12px;\n"
"  border: none;\n"
"  background: transparent;\n"
"  background-image: transparent;\n"
"  border: 0;\n"
"  margin: 0;\n"
"  padding: 0;\n"
"  image: url(\":/qss_icons/light/rc_light/window_close.png\");\n"
"}\n"
"\n"
"QDockWidget::close-button:hover {\n"
"  image: url(\":/qss_icons/light/rc_light/window_close_focus.pn"
                        "g\");\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed {\n"
"  image: url(\":/qss_icons/light/rc_light/window_close_pressed.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button {\n"
"  icon-size: 12px;\n"
"  border: none;\n"
"  background: transparent;\n"
"  background-image: transparent;\n"
"  border: 0;\n"
"  margin: 0;\n"
"  padding: 0;\n"
"  image: url(\":/qss_icons/light/rc_light/window_undock.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button:hover {\n"
"  image: url(\":/qss_icons/light/rc_light/window_undock_focus.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button:pressed {\n"
"  image: url(\":/qss_icons/light/rc_light/window_undock_pressed.png\");\n"
"}\n"
"\n"
"/* QTreeView QListView QTableView -----------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtreeview\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qlistview\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtableview\n"
"\n"
"-----------------------------------------"
                        "---------------------------------- */\n"
"QTreeView:branch:selected, QTreeView:branch:hover {\n"
"  background: url(\":/qss_icons/light/rc_light/transparent.png\");\n"
"}\n"
"\n"
"QTreeView:branch:has-siblings:!adjoins-item {\n"
"  border-image: url(\":/qss_icons/light/rc_light/branch_line.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:has-siblings:adjoins-item {\n"
"  border-image: url(\":/qss_icons/light/rc_light/branch_more.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:!has-children:!has-siblings:adjoins-item {\n"
"  border-image: url(\":/qss_icons/light/rc_light/branch_end.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:has-children:!has-siblings:closed, QTreeView:branch:closed:has-children:has-siblings {\n"
"  border-image: none;\n"
"  image: url(\":/qss_icons/light/rc_light/branch_closed.png\");\n"
"}\n"
"\n"
"QTreeView:branch:open:has-children:!has-siblings, QTreeView:branch:open:has-children:has-siblings {\n"
"  border-image: none;\n"
"  image: url(\":/qss_icons/light/rc_light/branch_open.png\");\n"
"}\n"
"\n"
"QTree"
                        "View:branch:has-children:!has-siblings:closed:hover, QTreeView:branch:closed:has-children:has-siblings:hover {\n"
"  image: url(\":/qss_icons/light/rc_light/branch_closed_focus.png\");\n"
"}\n"
"\n"
"QTreeView:branch:open:has-children:!has-siblings:hover, QTreeView:branch:open:has-children:has-siblings:hover {\n"
"  image: url(\":/qss_icons/light/rc_light/branch_open_focus.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:checked,\n"
"QListView::indicator:checked,\n"
"QTableView::indicator:checked,\n"
"QColumnView::indicator:checked {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:checked:hover, QTreeView::indicator:checked:focus, QTreeView::indicator:checked:pressed,\n"
"QListView::indicator:checked:hover,\n"
"QListView::indicator:checked:focus,\n"
"QListView::indicator:checked:pressed,\n"
"QTableView::indicator:checked:hover,\n"
"QTableView::indicator:checked:focus,\n"
"QTableView::indicator:checked:pressed,\n"
"QColumnView::indicator:checked:hover,\n"
"Q"
                        "ColumnView::indicator:checked:focus,\n"
"QColumnView::indicator:checked:pressed {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked,\n"
"QListView::indicator:unchecked,\n"
"QTableView::indicator:unchecked,\n"
"QColumnView::indicator:unchecked {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked:hover, QTreeView::indicator:unchecked:focus, QTreeView::indicator:unchecked:pressed,\n"
"QListView::indicator:unchecked:hover,\n"
"QListView::indicator:unchecked:focus,\n"
"QListView::indicator:unchecked:pressed,\n"
"QTableView::indicator:unchecked:hover,\n"
"QTableView::indicator:unchecked:focus,\n"
"QTableView::indicator:unchecked:pressed,\n"
"QColumnView::indicator:unchecked:hover,\n"
"QColumnView::indicator:unchecked:focus,\n"
"QColumnView::indicator:unchecked:pressed {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_unchecked_focus.png\");\n"
"}\n"
"\n"
"QTreeView::indi"
                        "cator:indeterminate,\n"
"QListView::indicator:indeterminate,\n"
"QTableView::indicator:indeterminate,\n"
"QColumnView::indicator:indeterminate {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_indeterminate.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:indeterminate:hover, QTreeView::indicator:indeterminate:focus, QTreeView::indicator:indeterminate:pressed,\n"
"QListView::indicator:indeterminate:hover,\n"
"QListView::indicator:indeterminate:focus,\n"
"QListView::indicator:indeterminate:pressed,\n"
"QTableView::indicator:indeterminate:hover,\n"
"QTableView::indicator:indeterminate:focus,\n"
"QTableView::indicator:indeterminate:pressed,\n"
"QColumnView::indicator:indeterminate:hover,\n"
"QColumnView::indicator:indeterminate:focus,\n"
"QColumnView::indicator:indeterminate:pressed {\n"
"  image: url(\":/qss_icons/light/rc_light/checkbox_indeterminate_focus.png\");\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView,\n"
"QTableView,\n"
"QColumnView {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px solid #C0C4C8;\n"
"  "
                        "color: #19232D;\n"
"  gridline-color: #C0C4C8;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTreeView:disabled,\n"
"QListView:disabled,\n"
"QTableView:disabled,\n"
"QColumnView:disabled {\n"
"  background-color: #FAFAFA;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QTreeView:selected,\n"
"QListView:selected,\n"
"QTableView:selected,\n"
"QColumnView:selected {\n"
"  background-color: #9FCBFF;\n"
"  color: #C0C4C8;\n"
"}\n"
"\n"
"QTreeView:focus,\n"
"QListView:focus,\n"
"QTableView:focus,\n"
"QColumnView:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"QTreeView::item:pressed,\n"
"QListView::item:pressed,\n"
"QTableView::item:pressed,\n"
"QColumnView::item:pressed {\n"
"  background-color: #9FCBFF;\n"
"}\n"
"\n"
"QTreeView::item:selected:active,\n"
"QListView::item:selected:active,\n"
"QTableView::item:selected:active,\n"
"QColumnView::item:selected:active {\n"
"  background-color: #9FCBFF;\n"
"}\n"
"\n"
"QTreeView::item:selected:!active,\n"
"QListView::item:selected:!active,\n"
"QTableView::item:selected:!active,\n"
""
                        "QColumnView::item:selected:!active {\n"
"  color: #19232D;\n"
"  background-color: #D2D5D8;\n"
"}\n"
"\n"
"QTreeView::item:!selected:hover,\n"
"QListView::item:!selected:hover,\n"
"QTableView::item:!selected:hover,\n"
"QColumnView::item:!selected:hover {\n"
"  outline: 0;\n"
"  color: #19232D;\n"
"  background-color: #D2D5D8;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"  background-color: #FAFAFA;\n"
"  border: 1px transparent #C0C4C8;\n"
"  border-radius: 0px;\n"
"}\n"
"\n"
"/* QHeaderView ------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qheaderview\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QHeaderView {\n"
"  background-color: #C0C4C8;\n"
"  border: 0px transparent #C0C4C8;\n"
"  padding: 0;\n"
"  margin: 0;\n"
"  border-radius: 0;\n"
"}\n"
"\n"
"QHeaderView:disabled {\n"
"  background-color: #C0C4C8;\n"
"  border: 1px transparent #C0C4C8;\n"
"}\n"
"\n"
"QHeaderView::section"
                        " {\n"
"  background-color: #C0C4C8;\n"
"  color: #19232D;\n"
"  border-radius: 0;\n"
"  text-align: left;\n"
"  font-size: 13px;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal {\n"
"  padding-top: 0;\n"
"  padding-bottom: 0;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-left: 1px solid #FAFAFA;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal::first, QHeaderView::section::horizontal::only-one {\n"
"  border-left: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:disabled {\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QHeaderView::section::vertical {\n"
"  padding-top: 0;\n"
"  padding-bottom: 0;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-top: 1px solid #FAFAFA;\n"
"}\n"
"\n"
"QHeaderView::section::vertical::first, QHeaderView::section::vertical::only-one {\n"
"  border-top: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"QHeaderView::section::vertical:disabled {\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"  /* Those settings (border/width/height/backgrou"
                        "nd-color) solve bug */\n"
"  /* transparent arrow background and size */\n"
"  background-color: #C0C4C8;\n"
"  border: none;\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down.png\");\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"  background-color: #C0C4C8;\n"
"  border: none;\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_up.png\");\n"
"}\n"
"\n"
"/* QToolBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolBox {\n"
"  padding: 0px;\n"
"  border: 0px;\n"
"  border: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"QToolBox:selected {\n"
"  padding: 0px;\n"
"  border: 2px solid #9FCBFF;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"  background-color: #FAFAFA;\n"
""
                        "  border: 1px solid #C0C4C8;\n"
"  color: #19232D;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QToolBox::tab:disabled {\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"  background-color: #ACB1B6;\n"
"  border-bottom: 2px solid #9FCBFF;\n"
"}\n"
"\n"
"QToolBox::tab:selected:disabled {\n"
"  background-color: #C0C4C8;\n"
"  border-bottom: 2px solid #DAEDFF;\n"
"}\n"
"\n"
"QToolBox::tab:!selected {\n"
"  background-color: #C0C4C8;\n"
"  border-bottom: 2px solid #C0C4C8;\n"
"}\n"
"\n"
"QToolBox::tab:!selected:disabled {\n"
"  background-color: #FAFAFA;\n"
"}\n"
"\n"
"QToolBox::tab:hover {\n"
"  border-color: #73C7FF;\n"
"  border-bottom: 2px solid #73C7FF;\n"
"}\n"
"\n"
"QToolBox QScrollArea {\n"
"  padding: 0px;\n"
"  border: 0px;\n"
"  background-color: #FAFAFA;\n"
"}\n"
"\n"
"/* QFrame -----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qframe\n"
"https://doc.qt.io/qt-5"
                        "/qframe.html#-prop\n"
"https://doc.qt.io/qt-5/qframe.html#details\n"
"https://stackoverflow.com/questions/14581498/qt-stylesheet-for-hline-vline-color\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* (dot) .QFrame  fix #141, #126, #123 */\n"
".QFrame {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #C0C4C8;\n"
"  /* No frame */\n"
"  /* HLine */\n"
"  /* HLine */\n"
"}\n"
"\n"
".QFrame[frameShape=\"0\"] {\n"
"  border-radius: 4px;\n"
"  border: 1px transparent #C0C4C8;\n"
"}\n"
"\n"
".QFrame[frameShape=\"4\"] {\n"
"  max-height: 2px;\n"
"  border: none;\n"
"  background-color: #C0C4C8;\n"
"}\n"
"\n"
".QFrame[frameShape=\"5\"] {\n"
"  max-width: 2px;\n"
"  border: none;\n"
"  background-color: #C0C4C8;\n"
"}\n"
"\n"
"/* QSplitter --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qsplitter\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QSp"
                        "litter {\n"
"  background-color: #C0C4C8;\n"
"  spacing: 0px;\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"  background-color: #C0C4C8;\n"
"  border: 0px solid #FAFAFA;\n"
"  spacing: 0px;\n"
"  padding: 1px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"  background-color: #788D9C;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"  width: 5px;\n"
"  image: url(\":/qss_icons/light/rc_light/line_vertical.png\");\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"  height: 5px;\n"
"  image: url(\":/qss_icons/light/rc_light/line_horizontal.png\");\n"
"}\n"
"\n"
"/* QDateEdit, QDateTimeEdit -----------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QDateEdit, QDateTimeEdit {\n"
"  selection-background-color: #9FCBFF;\n"
"  border-style: solid;\n"
"  border: 1px solid #C0C4C8;\n"
"  border-radius: 4px;\n"
"  /* This fixes 103, 111 */\n"
"  padding-top: 2px;\n"
"  /* This fixes 103, 111 *"
                        "/\n"
"  padding-bottom: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  min-width: 10px;\n"
"}\n"
"\n"
"QDateEdit:on, QDateTimeEdit:on {\n"
"  selection-background-color: #9FCBFF;\n"
"}\n"
"\n"
"QDateEdit::drop-down, QDateTimeEdit::drop-down {\n"
"  subcontrol-origin: padding;\n"
"  subcontrol-position: top right;\n"
"  width: 12px;\n"
"  border-left: 1px solid #C0C4C8;\n"
"}\n"
"\n"
"QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on, QDateEdit::down-arrow:hover, QDateEdit::down-arrow:focus, QDateTimeEdit::down-arrow:on, QDateTimeEdit::down-arrow:hover, QDateTimeEdit::down-arrow:focus {\n"
"  image: url(\":/qss_icons/light/rc_light/arrow_down.png\");\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView, QDateTimeEdit QAbstractItemView {\n"
"  background-color: #FAFAFA;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #C0C4C8;\n"
"  selection-background-col"
                        "or: #9FCBFF;\n"
"}\n"
"\n"
"/* QAbstractView ----------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractView:hover {\n"
"  border: 1px solid #9FCBFF;\n"
"  color: #19232D;\n"
"}\n"
"\n"
"QAbstractView:selected {\n"
"  background: #9FCBFF;\n"
"  color: #C0C4C8;\n"
"}\n"
"\n"
"/* PlotWidget -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"PlotWidget {\n"
"  /* Fix cut labels in plots #134 */\n"
"  padding: 0px;\n"
"}\n"
""));
        EmployeeRecordView->setModal(true);
        verticalLayout = new QVBoxLayout(EmployeeRecordView);
        verticalLayout->setSpacing(20);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        verticalLayout_2 = new QVBoxLayout();
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        personalInfo_groupBox = new QGroupBox(EmployeeRecordView);
        personalInfo_groupBox->setObjectName(QString::fromUtf8("personalInfo_groupBox"));
        gridLayout_2 = new QGridLayout(personalInfo_groupBox);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        gridLayout_2->setHorizontalSpacing(20);
        horizontalLayout_8 = new QHBoxLayout();
        horizontalLayout_8->setObjectName(QString::fromUtf8("horizontalLayout_8"));
        education_label = new QLabel(personalInfo_groupBox);
        education_label->setObjectName(QString::fromUtf8("education_label"));
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(education_label->sizePolicy().hasHeightForWidth());
        education_label->setSizePolicy(sizePolicy);
        education_label->setMinimumSize(QSize(61, 0));

        horizontalLayout_8->addWidget(education_label);

        education_lineEdit = new QLineEdit(personalInfo_groupBox);
        education_lineEdit->setObjectName(QString::fromUtf8("education_lineEdit"));

        horizontalLayout_8->addWidget(education_lineEdit);


        gridLayout_2->addLayout(horizontalLayout_8, 2, 1, 1, 1);

        horizontalLayout_4 = new QHBoxLayout();
        horizontalLayout_4->setObjectName(QString::fromUtf8("horizontalLayout_4"));
        dob_label = new QLabel(personalInfo_groupBox);
        dob_label->setObjectName(QString::fromUtf8("dob_label"));
        sizePolicy.setHeightForWidth(dob_label->sizePolicy().hasHeightForWidth());
        dob_label->setSizePolicy(sizePolicy);
        dob_label->setMinimumSize(QSize(106, 0));

        horizontalLayout_4->addWidget(dob_label);

        dob_dateEdit = new QDateEdit(personalInfo_groupBox);
        dob_dateEdit->setObjectName(QString::fromUtf8("dob_dateEdit"));
        QSizePolicy sizePolicy1(QSizePolicy::Expanding, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(dob_dateEdit->sizePolicy().hasHeightForWidth());
        dob_dateEdit->setSizePolicy(sizePolicy1);
        dob_dateEdit->setCalendarPopup(true);

        horizontalLayout_4->addWidget(dob_dateEdit);


        gridLayout_2->addLayout(horizontalLayout_4, 1, 0, 1, 1);

        horizontalLayout_6 = new QHBoxLayout();
        horizontalLayout_6->setObjectName(QString::fromUtf8("horizontalLayout_6"));
        phone_label = new QLabel(personalInfo_groupBox);
        phone_label->setObjectName(QString::fromUtf8("phone_label"));
        sizePolicy.setHeightForWidth(phone_label->sizePolicy().hasHeightForWidth());
        phone_label->setSizePolicy(sizePolicy);
        phone_label->setMinimumSize(QSize(100, 0));

        horizontalLayout_6->addWidget(phone_label);

        phone_lineEdit = new QLineEdit(personalInfo_groupBox);
        phone_lineEdit->setObjectName(QString::fromUtf8("phone_lineEdit"));

        horizontalLayout_6->addWidget(phone_lineEdit);


        gridLayout_2->addLayout(horizontalLayout_6, 1, 2, 1, 1);

        horizontalLayout_2 = new QHBoxLayout();
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        name_label = new QLabel(personalInfo_groupBox);
        name_label->setObjectName(QString::fromUtf8("name_label"));
        sizePolicy.setHeightForWidth(name_label->sizePolicy().hasHeightForWidth());
        name_label->setSizePolicy(sizePolicy);
        name_label->setMinimumSize(QSize(61, 0));

        horizontalLayout_2->addWidget(name_label);

        name_lineEdit = new QLineEdit(personalInfo_groupBox);
        name_lineEdit->setObjectName(QString::fromUtf8("name_lineEdit"));

        horizontalLayout_2->addWidget(name_lineEdit);


        gridLayout_2->addLayout(horizontalLayout_2, 0, 1, 1, 1);

        horizontalLayout_3 = new QHBoxLayout();
        horizontalLayout_3->setObjectName(QString::fromUtf8("horizontalLayout_3"));
        gender_label = new QLabel(personalInfo_groupBox);
        gender_label->setObjectName(QString::fromUtf8("gender_label"));
        sizePolicy.setHeightForWidth(gender_label->sizePolicy().hasHeightForWidth());
        gender_label->setSizePolicy(sizePolicy);
        gender_label->setMinimumSize(QSize(100, 0));

        horizontalLayout_3->addWidget(gender_label);

        gender_comboBox = new QComboBox(personalInfo_groupBox);
        gender_comboBox->addItem(QString());
        gender_comboBox->addItem(QString());
        gender_comboBox->setObjectName(QString::fromUtf8("gender_comboBox"));
        sizePolicy1.setHeightForWidth(gender_comboBox->sizePolicy().hasHeightForWidth());
        gender_comboBox->setSizePolicy(sizePolicy1);

        horizontalLayout_3->addWidget(gender_comboBox);


        gridLayout_2->addLayout(horizontalLayout_3, 0, 2, 1, 1);

        horizontalLayout_7 = new QHBoxLayout();
        horizontalLayout_7->setObjectName(QString::fromUtf8("horizontalLayout_7"));
        salary_label = new QLabel(personalInfo_groupBox);
        salary_label->setObjectName(QString::fromUtf8("salary_label"));
        sizePolicy.setHeightForWidth(salary_label->sizePolicy().hasHeightForWidth());
        salary_label->setSizePolicy(sizePolicy);
        salary_label->setMinimumSize(QSize(106, 0));

        horizontalLayout_7->addWidget(salary_label);

        salary_doubleSpinBox = new QDoubleSpinBox(personalInfo_groupBox);
        salary_doubleSpinBox->setObjectName(QString::fromUtf8("salary_doubleSpinBox"));
        sizePolicy1.setHeightForWidth(salary_doubleSpinBox->sizePolicy().hasHeightForWidth());
        salary_doubleSpinBox->setSizePolicy(sizePolicy1);
        salary_doubleSpinBox->setMaximum(1000000000.000000000000000);
        salary_doubleSpinBox->setSingleStep(100000.000000000000000);

        horizontalLayout_7->addWidget(salary_doubleSpinBox);


        gridLayout_2->addLayout(horizontalLayout_7, 2, 0, 1, 1);

        horizontalLayout_1 = new QHBoxLayout();
        horizontalLayout_1->setObjectName(QString::fromUtf8("horizontalLayout_1"));
        id_label = new QLabel(personalInfo_groupBox);
        id_label->setObjectName(QString::fromUtf8("id_label"));
        sizePolicy.setHeightForWidth(id_label->sizePolicy().hasHeightForWidth());
        id_label->setSizePolicy(sizePolicy);
        id_label->setMinimumSize(QSize(106, 0));

        horizontalLayout_1->addWidget(id_label);

        id_lineEdit = new QLineEdit(personalInfo_groupBox);
        id_lineEdit->setObjectName(QString::fromUtf8("id_lineEdit"));

        horizontalLayout_1->addWidget(id_lineEdit);


        gridLayout_2->addLayout(horizontalLayout_1, 0, 0, 1, 1);

        horizontalLayout_5 = new QHBoxLayout();
        horizontalLayout_5->setObjectName(QString::fromUtf8("horizontalLayout_5"));
        address_label = new QLabel(personalInfo_groupBox);
        address_label->setObjectName(QString::fromUtf8("address_label"));
        sizePolicy.setHeightForWidth(address_label->sizePolicy().hasHeightForWidth());
        address_label->setSizePolicy(sizePolicy);
        address_label->setMinimumSize(QSize(61, 0));

        horizontalLayout_5->addWidget(address_label);

        address_lineEdit = new QLineEdit(personalInfo_groupBox);
        address_lineEdit->setObjectName(QString::fromUtf8("address_lineEdit"));

        horizontalLayout_5->addWidget(address_lineEdit);


        gridLayout_2->addLayout(horizontalLayout_5, 1, 1, 1, 1);

        horizontalLayout_9 = new QHBoxLayout();
        horizontalLayout_9->setObjectName(QString::fromUtf8("horizontalLayout_9"));
        role_label = new QLabel(personalInfo_groupBox);
        role_label->setObjectName(QString::fromUtf8("role_label"));
        sizePolicy.setHeightForWidth(role_label->sizePolicy().hasHeightForWidth());
        role_label->setSizePolicy(sizePolicy);
        role_label->setMinimumSize(QSize(100, 0));

        horizontalLayout_9->addWidget(role_label);

        role_comboBox = new QComboBox(personalInfo_groupBox);
        role_comboBox->addItem(QString());
        role_comboBox->addItem(QString());
        role_comboBox->addItem(QString());
        role_comboBox->setObjectName(QString::fromUtf8("role_comboBox"));
        sizePolicy1.setHeightForWidth(role_comboBox->sizePolicy().hasHeightForWidth());
        role_comboBox->setSizePolicy(sizePolicy1);

        horizontalLayout_9->addWidget(role_comboBox);


        gridLayout_2->addLayout(horizontalLayout_9, 2, 2, 1, 1);

        gridLayout_2->setColumnStretch(0, 3);
        gridLayout_2->setColumnStretch(1, 4);
        gridLayout_2->setColumnStretch(2, 3);

        verticalLayout_2->addWidget(personalInfo_groupBox);

        detailInfo_groupBox = new QGroupBox(EmployeeRecordView);
        detailInfo_groupBox->setObjectName(QString::fromUtf8("detailInfo_groupBox"));
        gridLayout = new QGridLayout(detailInfo_groupBox);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setHorizontalSpacing(20);
        specialty_horizontalLayout = new QHBoxLayout();
        specialty_horizontalLayout->setObjectName(QString::fromUtf8("specialty_horizontalLayout"));
        specialty_label = new QLabel(detailInfo_groupBox);
        specialty_label->setObjectName(QString::fromUtf8("specialty_label"));
        sizePolicy.setHeightForWidth(specialty_label->sizePolicy().hasHeightForWidth());
        specialty_label->setSizePolicy(sizePolicy);
        specialty_label->setMinimumSize(QSize(80, 0));

        specialty_horizontalLayout->addWidget(specialty_label);

        specialty_lineEdit = new QLineEdit(detailInfo_groupBox);
        specialty_lineEdit->setObjectName(QString::fromUtf8("specialty_lineEdit"));

        specialty_horizontalLayout->addWidget(specialty_lineEdit);


        gridLayout->addLayout(specialty_horizontalLayout, 0, 0, 1, 1);

        subsidies_horizontalLayout = new QHBoxLayout();
        subsidies_horizontalLayout->setObjectName(QString::fromUtf8("subsidies_horizontalLayout"));
        subsidies_label = new QLabel(detailInfo_groupBox);
        subsidies_label->setObjectName(QString::fromUtf8("subsidies_label"));
        sizePolicy.setHeightForWidth(subsidies_label->sizePolicy().hasHeightForWidth());
        subsidies_label->setSizePolicy(sizePolicy);
        subsidies_label->setMinimumSize(QSize(100, 0));

        subsidies_horizontalLayout->addWidget(subsidies_label);

        subsidies_doubleSpinBox = new QDoubleSpinBox(detailInfo_groupBox);
        subsidies_doubleSpinBox->setObjectName(QString::fromUtf8("subsidies_doubleSpinBox"));
        sizePolicy1.setHeightForWidth(subsidies_doubleSpinBox->sizePolicy().hasHeightForWidth());
        subsidies_doubleSpinBox->setSizePolicy(sizePolicy1);
        subsidies_doubleSpinBox->setMaximum(1000000000.000000000000000);
        subsidies_doubleSpinBox->setSingleStep(100000.000000000000000);

        subsidies_horizontalLayout->addWidget(subsidies_doubleSpinBox);


        gridLayout->addLayout(subsidies_horizontalLayout, 0, 1, 1, 1);

        duty_horizontalLayout = new QHBoxLayout();
        duty_horizontalLayout->setObjectName(QString::fromUtf8("duty_horizontalLayout"));
        duty_label = new QLabel(detailInfo_groupBox);
        duty_label->setObjectName(QString::fromUtf8("duty_label"));
        sizePolicy.setHeightForWidth(duty_label->sizePolicy().hasHeightForWidth());
        duty_label->setSizePolicy(sizePolicy);

        duty_horizontalLayout->addWidget(duty_label);

        duty_lineEdit = new QLineEdit(detailInfo_groupBox);
        duty_lineEdit->setObjectName(QString::fromUtf8("duty_lineEdit"));

        duty_horizontalLayout->addWidget(duty_lineEdit);


        gridLayout->addLayout(duty_horizontalLayout, 0, 2, 1, 1);

        license_horizontalLayout = new QHBoxLayout();
        license_horizontalLayout->setObjectName(QString::fromUtf8("license_horizontalLayout"));
        license_label = new QLabel(detailInfo_groupBox);
        license_label->setObjectName(QString::fromUtf8("license_label"));
        sizePolicy.setHeightForWidth(license_label->sizePolicy().hasHeightForWidth());
        license_label->setSizePolicy(sizePolicy);
        license_label->setMinimumSize(QSize(80, 0));

        license_horizontalLayout->addWidget(license_label);

        license_lineEdit = new QLineEdit(detailInfo_groupBox);
        license_lineEdit->setObjectName(QString::fromUtf8("license_lineEdit"));

        license_horizontalLayout->addWidget(license_lineEdit);


        gridLayout->addLayout(license_horizontalLayout, 1, 0, 1, 1);

        workingDays_horizontalLayout = new QHBoxLayout();
        workingDays_horizontalLayout->setObjectName(QString::fromUtf8("workingDays_horizontalLayout"));
        workingDays_label = new QLabel(detailInfo_groupBox);
        workingDays_label->setObjectName(QString::fromUtf8("workingDays_label"));
        sizePolicy.setHeightForWidth(workingDays_label->sizePolicy().hasHeightForWidth());
        workingDays_label->setSizePolicy(sizePolicy);
        workingDays_label->setMinimumSize(QSize(100, 0));

        workingDays_horizontalLayout->addWidget(workingDays_label);

        workingDays_spinBox = new QSpinBox(detailInfo_groupBox);
        workingDays_spinBox->setObjectName(QString::fromUtf8("workingDays_spinBox"));
        sizePolicy1.setHeightForWidth(workingDays_spinBox->sizePolicy().hasHeightForWidth());
        workingDays_spinBox->setSizePolicy(sizePolicy1);
        workingDays_spinBox->setMaximum(31);

        workingDays_horizontalLayout->addWidget(workingDays_spinBox);


        gridLayout->addLayout(workingDays_horizontalLayout, 1, 1, 1, 1);

        gridLayout->setColumnStretch(0, 4);
        gridLayout->setColumnStretch(1, 4);
        gridLayout->setColumnStretch(2, 5);

        verticalLayout_2->addWidget(detailInfo_groupBox);

        verticalLayout_2->setStretch(0, 3);
        verticalLayout_2->setStretch(1, 2);

        verticalLayout->addLayout(verticalLayout_2);

        buttonBox = new QDialogButtonBox(EmployeeRecordView);
        buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);

        verticalLayout->addWidget(buttonBox);

        QWidget::setTabOrder(id_lineEdit, name_lineEdit);
        QWidget::setTabOrder(name_lineEdit, gender_comboBox);
        QWidget::setTabOrder(gender_comboBox, dob_dateEdit);
        QWidget::setTabOrder(dob_dateEdit, address_lineEdit);
        QWidget::setTabOrder(address_lineEdit, phone_lineEdit);
        QWidget::setTabOrder(phone_lineEdit, salary_doubleSpinBox);
        QWidget::setTabOrder(salary_doubleSpinBox, education_lineEdit);
        QWidget::setTabOrder(education_lineEdit, role_comboBox);
        QWidget::setTabOrder(role_comboBox, specialty_lineEdit);
        QWidget::setTabOrder(specialty_lineEdit, license_lineEdit);
        QWidget::setTabOrder(license_lineEdit, subsidies_doubleSpinBox);
        QWidget::setTabOrder(subsidies_doubleSpinBox, workingDays_spinBox);
        QWidget::setTabOrder(workingDays_spinBox, duty_lineEdit);

        retranslateUi(EmployeeRecordView);
        QObject::connect(buttonBox, SIGNAL(accepted()), EmployeeRecordView, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), EmployeeRecordView, SLOT(reject()));

        QMetaObject::connectSlotsByName(EmployeeRecordView);
    } // setupUi

    void retranslateUi(QDialog *EmployeeRecordView)
    {
        EmployeeRecordView->setWindowTitle(QCoreApplication::translate("EmployeeRecordView", "EmployeeRecordView", nullptr));
        personalInfo_groupBox->setTitle(QCoreApplication::translate("EmployeeRecordView", "Th\303\264ng tin c\303\241 nh\303\242n", nullptr));
        education_label->setText(QCoreApplication::translate("EmployeeRecordView", "H\341\273\215c v\341\273\213:", nullptr));
        dob_label->setText(QCoreApplication::translate("EmployeeRecordView", "Ng\303\240y sinh:", nullptr));
        phone_label->setText(QCoreApplication::translate("EmployeeRecordView", "S\341\273\221 \304\221i\341\273\207n tho\341\272\241i:", nullptr));
        name_label->setText(QCoreApplication::translate("EmployeeRecordView", "H\341\273\215 t\303\252n:", nullptr));
        gender_label->setText(QCoreApplication::translate("EmployeeRecordView", "Gi\341\273\233i t\303\255nh:", nullptr));
        gender_comboBox->setItemText(0, QCoreApplication::translate("EmployeeRecordView", "Nam", nullptr));
        gender_comboBox->setItemText(1, QCoreApplication::translate("EmployeeRecordView", "N\341\273\257", nullptr));

        salary_label->setText(QCoreApplication::translate("EmployeeRecordView", "L\306\260\306\241ng c\306\241 b\341\272\243n:", nullptr));
        id_label->setText(QCoreApplication::translate("EmployeeRecordView", "M\303\243 nh\303\242n vi\303\252n:", nullptr));
        address_label->setText(QCoreApplication::translate("EmployeeRecordView", "\304\220\341\273\213a ch\341\273\211:", nullptr));
        role_label->setText(QCoreApplication::translate("EmployeeRecordView", "Vai tr\303\262:", nullptr));
        role_comboBox->setItemText(0, QCoreApplication::translate("EmployeeRecordView", "B\303\241c s\304\251", nullptr));
        role_comboBox->setItemText(1, QCoreApplication::translate("EmployeeRecordView", "Y t\303\241", nullptr));
        role_comboBox->setItemText(2, QCoreApplication::translate("EmployeeRecordView", "Ti\341\272\277p t\303\242n", nullptr));

        detailInfo_groupBox->setTitle(QCoreApplication::translate("EmployeeRecordView", "Th\303\264ng tin chi ti\341\272\277t", nullptr));
        specialty_label->setText(QCoreApplication::translate("EmployeeRecordView", "M\303\243 khoa:", nullptr));
        subsidies_label->setText(QCoreApplication::translate("EmployeeRecordView", "Tr\341\273\243 c\341\272\245p:", nullptr));
        duty_label->setText(QCoreApplication::translate("EmployeeRecordView", "Tr\303\241ch nhi\341\273\207m:", nullptr));
        license_label->setText(QCoreApplication::translate("EmployeeRecordView", "Gi\341\272\245y ph\303\251p:", nullptr));
        workingDays_label->setText(QCoreApplication::translate("EmployeeRecordView", "S\341\273\221 ng\303\240y l\303\240m:", nullptr));
    } // retranslateUi

};

namespace Ui {
    class EmployeeRecordView: public Ui_EmployeeRecordView {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EMPLOYEERECORDVIEW_H
